# Generated by Django 4.2.13 on 2024-06-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joven',
        ),
    ]
