# Generated by Django 3.2.4 on 2025-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambiar_contrasena',
            field=models.BooleanField(default=True),
        ),
    ]
