# Generated by Django 3.2.4 on 2024-08-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20240814_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
