# Generated by Django 3.2.4 on 2024-07-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
    ]
