# Generated by Django 3.2.4 on 2025-08-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_usuario_cambiar_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cambiar_contrasena',
        ),
    ]
