# Generated by Django 3.2.4 on 2024-07-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_delete_joven'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='horas_requeridas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
