# Generated by Django 3.2.4 on 2024-07-31 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_scan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
