# Generated by Django 3.2.4 on 2024-07-31 19:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_scan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
