# Generated by Django 3.2.4 on 2024-08-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_delete_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_entrada_fecha', models.DateTimeField(auto_now_add=True)),
                ('qr_salida_fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_escaneo_entrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_escaneo_salida', models.DateTimeField(blank=True, null=True)),
                ('horas', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.usuario')),
            ],
        ),
    ]
