# Generated by Django 3.2.4 on 2024-07-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_auto_20240731_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_scan',
        ),
    ]
