# Generated by Django 3.2.4 on 2024-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_remove_asistencia_fecha_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_scan',
            field=models.DateTimeField(auto_now_add=True, default='now'),
            preserve_default=False,
        ),
    ]
