# Generated by Django 3.2.4 on 2024-08-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_asistencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.usuario'),
        ),
    ]
