# Generated by Django 3.2.4 on 2024-08-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_auto_20240731_1352'),
        ('asistencia', '0004_auto_20240731_1418'),
        ('asistencia', '0007_alter_asistencia_fecha_scan'),
    ]

    operations = [
    ]
