# Generated by Django 3.2.4 on 2024-08-06 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_merge_20240806_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_scan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
